services:
  postgres:
    image: postgres:18
    container_name: trendy-postgres
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      PGDATA: /var/lib/postgresql/data
    ports:
      - "5532:5432"
    networks:
      - banking
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init-multi-db.sql:/docker-entrypoint-initdb.d/init.sql

  keycloak_postgres:
    image: postgres:18
    container_name: trendy-keycloak-db
    restart: always
    environment:
      POSTGRES_DB: ${KEYCLOAK_DB_NAME}
      POSTGRES_USER: ${KEYCLOAK_DB_USER}
      POSTGRES_PASSWORD: ${KEYCLOAK_DB_PASSWORD}
      PGDATA: /var/lib/postgresql/data
    ports:
      - "5533:5432"
    networks:
      - banking
    volumes:
      - keycloak_pgdata:/var/lib/postgresql/data
    depends_on:
      - postgres

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: trendy-pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - "6060:80"
    depends_on:
      - postgres
    networks:
      - banking
    volumes:
      - pgadmin_data:/var/lib/pgadmin

  keycloak:
    image: quay.io/keycloak/keycloak:26.5.2
    container_name: trendy-keycloak
    command: start-dev
    environment:
      KC_DB: postgres
      KC_DB_URL_HOST: keycloak_postgres
      KC_DB_URL_DATABASE: ${KEYCLOAK_DB_NAME}
      KC_DB_USERNAME: ${KEYCLOAK_DB_USER}
      KC_DB_PASSWORD: ${KEYCLOAK_DB_PASSWORD}
      KC_BOOTSTRAP_ADMIN_USERNAME: ${KEYCLOAK_ADMIN_USERNAME}
      KC_BOOTSTRAP_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}
    ports:
      - "127.0.0.1:8443:8080"
      - "19000:9000"
    networks:
      - banking
    depends_on:
      - postgres

  redis:
    image: redis:8-alpine
    container_name: trendy-redis
    restart: unless-stopped
    command: >
      redis-server
      --appendonly yes
      --requirepass ${REDIS_PASSWORD}
    ports:
      - "127.0.0.1:6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - banking

volumes:
  pgdata:
  pgadmin_data:
  keycloak_pgdata:
  redis_data:

networks:
  banking:
    driver: bridge
