spring:
  application:
    name: core-banking-backend

  datasource:
    url: jdbc:postgresql://localhost:5532/bankdb
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8443/realms/trendy-bank

  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      password: ${REDIS_PASSWORD}
      timeout: 5s

logging:
  level:
    org.springframework.security: DEBUG

keycloak:
  server-url: ${KEYCLOAK_BASE_URL}
  realm: ${KEYCLOAK_REALM_NAME}
  public-client-id: ${KEYCLOAK_PUBLIC_CLIENT_ID}
  admin-realm: ${KEYCLOAK_ADMIN_REALM_NAME}
  admin-client-id: ${KEYCLOAK_ADMIN_CLIENT_ID}
  admin-client-secret: ${KEYCLOAK_ADMIN_CLIENT_SECRET}

app:
  auth:
    cookie-secure: false
    cookie-same-site: "Lax"
    cookie-domain: ${COOKIE_DOMAIN}