package com.trendy.cbs.enums;

public enum ErrorCode {
    CUSTOMER_NOT_VERIFIED,
    CUSTOMER_NOT_ACTIVE,
    IDENTITY_NOT_COMPLETED,
    ACCOUNT_LIMIT_REACHED,
    INVALID_AMOUNT,
    INSUFFICIENT_BALANCE,
    INVALID_OPERATION,

    USERNAME_ALREADY_EXISTS,
    EMAIL_ALREADY_EXISTS,
    PHONE_ALREADY_EXISTS,
    CUSTOMER_ALREADY_EXISTS,
    INVALID_CREDENTIALS,
    ACCESS_DENIED,
    KEYCLOAK_USER_CREATE_FAILED,
    AUTH_ERROR
}
